### ISSUE TITLE
Need a formal release number

### ISSUE THREAD

**Issue by fossfreedom** [getsolus/budgie-screensaver#3]
Please tag the repo with the latest recommended release number so that distros such as Debian and Ubuntu can use the project utilising your recommended codebase commit.

TIA

**Comment by JoshStrobl** [comment]
Yep, will do this when I tag a new release of Budgie!

**Comment by fossfreedom** [comment]
If you can do this sooner rather than later I would much appreciate it.  Without it I cannot submit the package to Debian - and since it can take several months to get a package into Debian there is a danger budgie desktop will be removed post release of bullseye.

**Comment by JoshStrobl** [comment]
Release planned for next Tuesday for v4.0 with the given rebranding changes and 5631e153e3cffb26cdabcec5925f9e2433ba23b3
